# Generated by Django 3.0.4 on 2020-04-10 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_point', models.CharField(default='', max_length=15, null=True, verbose_name='House Name (Land Mark if not home address).')),
                ('place', models.CharField(max_length=15)),
                ('zip_code', models.IntegerField()),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='default/staff_profile.png', upload_to='staff/profile_pictures')),
                ('phone', models.IntegerField()),
                ('lockdown', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Address')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=15)),
                ('department_description', models.CharField(max_length=50)),
                ('is_medical', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.FloatField()),
                ('level_description', models.CharField(max_length=50)),
                ('max_leaves', models.IntegerField(null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=20)),
                ('amnt_for_one', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_now', models.IntegerField(null=True)),
                ('last_refill_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthReccord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companion_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='companion name (optional)')),
                ('companion_phone', models.IntegerField(blank=True, null=True, verbose_name='companion phone (optional)')),
                ('status_code', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('op_time_stamp', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Department')),
                ('diseases', models.ManyToManyField(blank=True, to='HospitalManagementSystem.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=20)),
                ('q_abbr', models.CharField(max_length=8)),
                ('q_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
                ('daily_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(default='Unspecified', max_length=30)),
                ('organ_under_surgery', models.CharField(default='Unspecified', max_length=20)),
                ('reason', models.CharField(default='Unspecified', max_length=20)),
                ('theatre', models.CharField(default='Unspecified', max_length=20)),
                ('total_amnt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prepay_amnt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_prepaid', models.BooleanField(default=False, verbose_name='Prepayment made')),
                ('date_of_surgery', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True, verbose_name='start time (you can change it later)')),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.TimeField(null=True)),
                ('patient_report_time', models.TimeField(blank=True, null=True)),
                ('team_report_time', models.TimeField(blank=True, null=True)),
                ('surgery_report', models.TextField(default='Surgery not over', max_length=400)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientHealthReccord')),
                ('team', models.ManyToManyField(blank=True, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=20)),
                ('test_abbr', models.CharField(max_length=8)),
                ('test_description', models.CharField(max_length=50)),
                ('test_amnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=250, null=True)),
                ('time_ordered', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DateTimeField(null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientHealthReccord')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Test')),
            ],
        ),
        migrations.CreateModel(
            name='TRDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='No title', max_length=30, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='patients', verbose_name='Document File')),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.TestResults')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='what is this photo? ')),
                ('photo', models.FileField(blank=True, null=True, upload_to='patients', verbose_name='Document File')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Surgery')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sName', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Country')),
            ],
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(max_length=800)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('next_turn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_sal', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
                ('exp_increment', models.FloatField(default=0)),
                ('other_increment', models.FloatField(default=0)),
                ('fine', models.FloatField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=5, unique=True)),
                ('vacant_beds', models.IntegerField()),
                ('roomtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requird_num', models.IntegerField(verbose_name='required number of items')),
                ('item_gained', models.IntegerField(default=-1)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' total price (deducting discount)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_to_buy', to='HospitalManagementSystem.Department')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_number', models.IntegerField(null=True, verbose_name='Total days')),
                ('med_freq', models.IntegerField(null=True)),
                ('is_given', models.BooleanField(default=False)),
                ('given_date', models.DateTimeField(null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Medicine')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientHealthReccord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientUnknown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identity_marks', models.CharField(blank=True, max_length=500, null=True)),
                ('estimated_age', models.IntegerField(null=True)),
                ('other_known_informations', models.CharField(blank=True, max_length=500, null=True)),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='unknown')),
                ('patient_gentder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outwrad', models.BooleanField(default=None, null=True, verbose_name='Transferring to another hospital (No, if transferring is to this hospital)')),
                ('transfer_time', models.DateTimeField(null=True, verbose_name='Date and time of transfer')),
                ('remarks', models.TextField(max_length=300)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientHealthReccord')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPersonalReccord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_Fname', models.CharField(max_length=20)),
                ('p_Lname', models.CharField(max_length=20)),
                ('p_age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_visited_date', models.DateTimeField(null=True)),
                ('next_meeting_date', models.DateTimeField(null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='patients', verbose_name='Document File')),
                ('p_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Address')),
                ('p_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Gender')),
            ],
        ),
        migrations.AddField(
            model_name='patienthealthreccord',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientPersonalReccord'),
        ),
        migrations.AddField(
            model_name='patienthealthreccord',
            name='patient_unknown',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientUnknown'),
        ),
        migrations.CreateModel(
            name='PatientAssociatedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, verbose_name='what is this photo? ')),
                ('photo', models.FileField(blank=True, null=True, upload_to='patients', verbose_name='Document File')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('approved', models.BooleanField(default=None, null=True)),
                ('reason', models.TextField(default='Unspecified', max_length=500, verbose_name='why do you do this?')),
                ('canceled', models.BooleanField(default=False, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=30)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('h_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Address')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRemarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_text', models.TextField(blank=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientHealthReccord')),
                ('remark_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='EMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.BooleanField(default=True)),
                ('subject', models.CharField(default='no subject', max_length=50)),
                ('text', models.TextField()),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.DateTimeField(null=True)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser', verbose_name='To')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.State')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='known_medicines',
            field=models.ManyToManyField(blank=True, to='HospitalManagementSystem.Medicine'),
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Department')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_inventories', to='HospitalManagementSystem.Department')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintsFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compaint', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField(max_length=200, verbose_name='Complaint')),
                ('time_filed', models.DateTimeField(auto_now_add=True)),
                ('concerned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Department')),
                ('concerned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_concerned', to='HospitalManagementSystem.AppUser')),
                ('on_behalf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.PatientPersonalReccord')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tests', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surgeries', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('room', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consult_and_ticket_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_time', models.DateTimeField(null=True)),
                ('concluded', models.BooleanField(default=False)),
                ('total_payed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amt_so_far', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('time_of_attendance', models.DateTimeField(auto_now_add=True)),
                ('time_of_leave', models.DateTimeField(null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Department'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='pro_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Level'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='qualifications',
            field=models.ManyToManyField(to='HospitalManagementSystem.Qualification'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Shift'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='staff_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Gender'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=200)),
                ('time_of_announcement', models.DateTimeField(auto_now_add=True)),
                ('from_u', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser')),
                ('target_department', models.ManyToManyField(to='HospitalManagementSystem.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_time', models.DateTimeField(null=True)),
                ('dis_time', models.DateTimeField(null=True)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Room')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.District'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(blank=True, max_length=30)),
                ('photo', models.FileField(blank=True, upload_to='staff/certificates')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.AppUser')),
            ],
            options={
                'unique_together': {('staff', 'certificate_title')},
            },
        ),
    ]
