# Generated by Django 3.0.4 on 2020-04-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='date_of_surgery',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='patient_report_time',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='team_report_time',
        ),
    ]
