# Generated by Django 3.0.4 on 2020-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0002_auto_20200410_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='date_of_surgery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='patient_report_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start time (you can change it later)'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='team_report_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
