# Generated by Django 3.0.4 on 2020-04-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0003_auto_20200410_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='next_turn',
        ),
    ]
