# Generated by Django 3.0.4 on 2020-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0005_shift_next_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='closed',
            field=models.BooleanField(default=None, null=True, verbose_name='is this order closed?'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='item_gained',
            field=models.IntegerField(default=0),
        ),
    ]
