# Generated by Django 3.0.4 on 2020-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0006_auto_20200412_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='aquired_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
