# Generated by Django 3.0.4 on 2020-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0007_purchaselist_aquired_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='concluded',
        ),
        migrations.AlterField(
            model_name='leaveapplications',
            name='canceled',
            field=models.BooleanField(default=None, null=True, verbose_name='cancel'),
        ),
    ]
