# Generated by Django 3.0.4 on 2020-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0008_auto_20200412_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
