# Generated by Django 3.0.4 on 2020-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0009_bill_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
