# Generated by Django 3.0.4 on 2020-04-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0010_auto_20200413_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientunknown',
            name='identity_document',
        ),
        migrations.AddField(
            model_name='patientunknown',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='unknown', verbose_name='identity document'),
        ),
    ]
