# Generated by Django 3.0.4 on 2020-04-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0011_auto_20200414_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpersonalreccord',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
