# Generated by Django 3.0.4 on 2020-04-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0012_patientpersonalreccord_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_of_leave',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
