# Generated by Django 3.0.4 on 2020-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0013_auto_20200415_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='occupabili',
            field=models.BooleanField(default=True),
        ),
    ]
