# Generated by Django 3.0.4 on 2020-04-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0014_appuser_occupabili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
