# Generated by Django 3.0.4 on 2020-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0015_auto_20200418_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='is_dismissal',
            field=models.BooleanField(default=False),
        ),
    ]
