# Generated by Django 3.0.4 on 2020-04-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0016_disciplinaryaction_is_dismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='is_complete',
            field=models.BooleanField(default=None, null=True, verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='is_dismissal',
            field=models.BooleanField(default=None, null=True, verbose_name='dismissed'),
        ),
    ]
