# Generated by Django 3.0.4 on 2020-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0017_auto_20200418_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsfeedback',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
