# Generated by Django 3.0.4 on 2020-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0019_auto_20200418_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsfeedback',
            name='concluded',
            field=models.BooleanField(null=True),
        ),
    ]
