# Generated by Django 3.0.4 on 2020-04-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0021_auto_20200418_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreport',
            name='remark_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remarks_made', to='HospitalManagementSystem.AppUser'),
        ),
    ]
