# Generated by Django 3.0.4 on 2020-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0023_staffreport_stop_editing'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='reason',
            field=models.TextField(default='agargagafffaadsf', max_length=300),
            preserve_default=False,
        ),
    ]
