# Generated by Django 3.0.4 on 2020-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0024_disciplinaryaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreport',
            name='filed_date',
            field=models.DateField(null=True),
        ),
    ]
