# Generated by Django 3.0.4 on 2020-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0025_staffreport_filed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreport',
            name='filed_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
