# Generated by Django 3.0.4 on 2020-04-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0028_staffreport_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreport',
            name='dismissed',
            field=models.BooleanField(default=None, verbose_name='dismiss this report from list'),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='stop_editing',
            field=models.BooleanField(default=None, verbose_name='stop editing of this report'),
        ),
    ]
