# Generated by Django 3.0.4 on 2020-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0029_auto_20200421_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=' total price (without discount)'),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='dismissed',
            field=models.BooleanField(default=False, null=True, verbose_name="move this report to 'reviewed list'"),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='stop_editing',
            field=models.BooleanField(default=False, null=True, verbose_name='stop editing of this report'),
        ),
    ]
