# Generated by Django 3.0.4 on 2020-04-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0030_auto_20200425_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Inventory'),
        ),
    ]
