# Generated by Django 3.0.4 on 2020-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0031_auto_20200425_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpersonalreccord',
            name='deceased',
            field=models.BooleanField(default=True),
        ),
    ]
