# Generated by Django 3.0.4 on 2020-04-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0032_patientpersonalreccord_deceased'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fatality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(verbose_name='date of death')),
                ('time_of', models.TimeField(verbose_name='time of death')),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientPersonalReccord')),
            ],
        ),
    ]
