# Generated by Django 3.0.4 on 2020-04-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0033_accident_fatality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatality',
            name='patient',
        ),
        migrations.AddField(
            model_name='fatality',
            name='hr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthealthreccord',
            name='accident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Accident'),
        ),
        migrations.CreateModel(
            name='Morgue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_no', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord')),
            ],
        ),
        migrations.CreateModel(
            name='Autopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(verbose_name='date of autopsy')),
                ('start_of', models.TimeField(verbose_name='start time of autopsy')),
                ('end_of', models.TimeField(verbose_name='end time of autopsy')),
                ('report', models.TextField()),
                ('head_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopsies_led', to='HospitalManagementSystem.AppUser')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientHealthReccord')),
                ('team', models.ManyToManyField(to='HospitalManagementSystem.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='fatality',
            name='autopsy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Autopsy'),
        ),
    ]
