# Generated by Django 3.0.4 on 2020-04-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0035_auto_20200426_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatality',
            name='date_of',
            field=models.DateField(blank=True, null=True, verbose_name='date of death'),
        ),
        migrations.AlterField(
            model_name='fatality',
            name='time_of',
            field=models.TimeField(blank=True, null=True, verbose_name='time of death'),
        ),
    ]
