# Generated by Django 3.0.4 on 2020-04-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0036_auto_20200426_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatality',
            name='autopsy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Surgery'),
        ),
    ]
