# Generated by Django 3.0.4 on 2020-04-28 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0037_auto_20200427_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatality',
            name='cause_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatality',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Disease'),
        ),
    ]
