# Generated by Django 3.0.4 on 2020-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0039_auto_20200428_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='is_autopsy',
            field=models.BooleanField(default=False),
        ),
    ]
