# Generated by Django 3.0.4 on 2020-04-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0042_auto_20200428_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
