# Generated by Django 3.0.4 on 2020-04-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0045_auto_20200428_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morgue',
            name='hr',
        ),
        migrations.AddField(
            model_name='morgue',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.PatientPersonalReccord'),
            preserve_default=False,
        ),
    ]
