# Generated by Django 3.0.4 on 2020-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0047_auto_20200430_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='morgue',
            name='morgue_service_only',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
