# Generated by Django 3.0.4 on 2020-04-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0048_morgue_morgue_service_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morgue',
            old_name='morgue_service_only',
            new_name='only_morgue_service',
        ),
    ]
