# Generated by Django 3.0.4 on 2020-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0049_auto_20200430_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='contagious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='fatality_rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
