# Generated by Django 3.0.4 on 2020-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0050_auto_20200430_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseOfDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_name', models.CharField(max_length=50)),
                ('cause_description', models.TextField(max_length=200)),
            ],
        ),
    ]
