# Generated by Django 3.0.4 on 2020-05-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0051_causeofdisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
                ('type_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='HumanOrgan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(max_length=30)),
                ('organ_class', models.IntegerField()),
                ('organ_description', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='contagious',
        ),
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.ManyToManyField(to='HospitalManagementSystem.CauseOfDisease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.DiseaseType'),
        ),
    ]
