# Generated by Django 3.0.4 on 2020-05-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0053_humanorgan_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanorgan',
            name='related_organs',
            field=models.ManyToManyField(to='HospitalManagementSystem.HumanOrgan'),
        ),
    ]
