# Generated by Django 3.0.4 on 2020-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0055_auto_20200506_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanorgan',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='organs'),
        ),
    ]
