# Generated by Django 3.0.4 on 2020-05-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0056_auto_20200506_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humanorgan',
            name='related_organs',
        ),
    ]
