# Generated by Django 3.0.4 on 2020-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0057_remove_humanorgan_related_organs'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanorgan',
            name='related_organs',
            field=models.ManyToManyField(blank=True, to='HospitalManagementSystem.HumanOrgan'),
        ),
    ]
