# Generated by Django 3.0.4 on 2020-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0060_auto_20200508_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatality',
            name='death_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
