# Generated by Django 3.0.4 on 2020-05-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0061_fatality_death_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreccord',
            name='departments',
            field=models.ManyToManyField(to='HospitalManagementSystem.Department'),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_of', to='HospitalManagementSystem.Department'),
        ),
    ]
