# Generated by Django 3.0.4 on 2020-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0062_auto_20200509_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthealthreccord',
            name='departments',
        ),
    ]
