# Generated by Django 3.0.4 on 2020-05-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0063_remove_patienthealthreccord_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatality',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser'),
        ),
    ]
