# Generated by Django 3.0.4 on 2020-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0065_surgery_initiated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientassociatedfiles',
            name='title',
            field=models.CharField(blank=True, default='untitled', max_length=25, verbose_name='what is this photo? '),
        ),
    ]
