# Generated by Django 3.0.4 on 2020-05-12 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0066_auto_20200512_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatality',
            name='cause_disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Disease'),
        ),
        migrations.AlterField(
            model_name='fatality',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aaa', to='HospitalManagementSystem.Disease'),
        ),
    ]
