# Generated by Django 3.0.4 on 2020-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0067_auto_20200512_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
