# Generated by Django 3.0.4 on 2020-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0068_auto_20200513_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='base_sal',
        ),
        migrations.AlterField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='exp_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='other_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
