# Generated by Django 3.0.4 on 2020-05-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0069_auto_20200515_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='exp_increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='experience increment'),
        ),
    ]
