# Generated by Django 3.0.4 on 2020-05-15 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0070_auto_20200515_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='issued_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
