# Generated by Django 3.0.4 on 2020-05-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0071_auto_20200515_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='fine',
        ),
    ]
