# Generated by Django 3.0.4 on 2020-05-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0072_remove_salary_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='is_complete',
            field=models.BooleanField(default=None, null=True, verbose_name='mark as completed'),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_records', to='HospitalManagementSystem.Department'),
        ),
    ]
