# Generated by Django 3.0.4 on 2020-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0074_auto_20200516_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
