# Generated by Django 3.0.4 on 2020-05-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0075_appuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='organ_under_surgery',
            field=models.CharField(default='Unspecified', max_length=20, null=True),
        ),
    ]
