# Generated by Django 3.0.4 on 2020-05-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0076_auto_20200518_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='organ_under_surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.HumanOrgan'),
        ),
    ]
