# Generated by Django 3.0.4 on 2020-05-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0077_auto_20200518_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='morgue',
            name='amnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='accident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Accident'),
        ),
    ]
