# Generated by Django 3.0.4 on 2020-05-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0079_auto_20200521_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselist',
            name='aquired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
