# Generated by Django 3.0.4 on 2020-06-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0081_auto_20200531_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='team leader must be chosen', to='HospitalManagementSystem.AppUser'),
        ),
    ]
