# Generated by Django 3.0.4 on 2020-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0082_auto_20200601_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='op_time_stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
