# Generated by Django 3.0.4 on 2020-06-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0083_auto_20200602_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsfeedback',
            name='authority_remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
