# Generated by Django 3.0.4 on 2020-06-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0085_auto_20200604_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreccord',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='affiliated_healthrecords', to='HospitalManagementSystem.Department'),
        ),
        migrations.AlterField(
            model_name='patientpersonalreccord',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='patients', verbose_name='photo/identity File'),
        ),
    ]
