# Generated by Django 3.0.4 on 2020-06-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0087_remove_patienthealthreccord_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='departments',
            field=models.ManyToManyField(blank=True, to='HospitalManagementSystem.Department'),
        ),
    ]
