# Generated by Django 3.0.4 on 2020-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0088_auto_20200606_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientunknown',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
    ]
