# Generated by Django 3.0.4 on 2020-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0089_patientunknown_deceased'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='refund_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
