# Generated by Django 3.0.4 on 2020-06-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0090_auto_20200608_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='refund_description',
        ),
    ]
