# Generated by Django 3.0.4 on 2020-06-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0092_auto_20200608_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pres_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser'),
        ),
        migrations.AddField(
            model_name='testresults',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.AppUser'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='affected_organs',
            field=models.ManyToManyField(blank=True, to='HospitalManagementSystem.HumanOrgan'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.ManyToManyField(blank=True, null=True, to='HospitalManagementSystem.CauseOfDisease'),
        ),
    ]
