# Generated by Django 3.0.4 on 2020-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0093_auto_20200610_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='surgery_refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
