# Generated by Django 3.0.4 on 2020-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0095_auto_20200611_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='surgery_refund',
        ),
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.ManyToManyField(blank=True, null=True, to='HospitalManagementSystem.CauseOfDisease'),
        ),
    ]
