# Generated by Django 3.0.4 on 2020-06-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0096_auto_20200611_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatality',
            name='cause_disease',
        ),
        migrations.AlterField(
            model_name='departmentinventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Inventory'),
        ),
    ]
