# Generated by Django 3.0.4 on 2020-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0097_auto_20200614_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='causes',
            field=models.ManyToManyField(blank=True, to='HospitalManagementSystem.CauseOfDisease'),
        ),
    ]
