# Generated by Django 3.0.4 on 2020-06-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0098_auto_20200614_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatality',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Disease'),
        ),
    ]
