# Generated by Django 3.0.4 on 2020-06-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0099_auto_20200614_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='emessage',
            name='reciever_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HospitalManagementSystem.Department', verbose_name='To'),
        ),
    ]
