# Generated by Django 3.0.4 on 2020-06-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0102_auto_20200615_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreccord',
            name='op_time_stamp_change',
            field=models.IntegerField(default=0),
        ),
    ]
