# Generated by Django 3.0.4 on 2020-06-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0105_patienthealthreccord_op_time_stamp_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthreccord',
            name='departments_visited',
            field=models.ManyToManyField(blank=True, related_name='visited_patients', to='HospitalManagementSystem.Department'),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='op_time_stamp_change',
            field=models.IntegerField(default=0),
        ),
    ]
