# Generated by Django 3.0.4 on 2020-06-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalManagementSystem', '0106_auto_20200617_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthealthreccord',
            name='op_time_stamp_change',
        ),
        migrations.AlterField(
            model_name='disciplinaryaction',
            name='is_complete',
            field=models.BooleanField(default=None, null=True, verbose_name='mark as completed/ canceled'),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='companion_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='companion name'),
        ),
        migrations.AlterField(
            model_name='patienthealthreccord',
            name='companion_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='companion phone'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='next_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementSystem.Shift'),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='dismissed',
            field=models.BooleanField(default=False, null=True, verbose_name='report reviewed'),
        ),
    ]
